#!/bin/bash
# Auto-switch Konsole theme based on system theme
# Get current system color scheme (1=dark, 2=light)
scheme=$(qdbus6 org.freedesktop.portal.Desktop /org/freedesktop/portal/desktop org.freedesktop.portal.Settings.Read "org.freedesktop.appearance" "color-scheme" 2>/dev/null)

if [[ "$scheme" == "2" ]]; then
    # Light theme
    konsoleprofile colors=Light
else
    # Dark theme  
    konsoleprofile colors=Dark
fi
